### ISSUE TITLE
Downgrade guava to release 11.0.2

### ISSUE THREAD

**Issue by garcia-jj** [caelum/vraptor-cdi-provider#1]
Since the code must be compliant with Java 5, we need to downgrade guava to version 11.0.2. Versions greater than 12 need Java 6.

**Comment by lucascs** [comment]
I don't think CDI plugin should have this constraint... CDI is JavaEE 6 => 7, which is java 7 compliant.

**Comment by garcia-jj** [comment]
So pom.xml must be changed, removing restriction to Java 5.

**Comment by lucascs** [comment]
fair enough =)
