### ISSUE TITLE
Change maven artifact group

### ISSUE THREAD

**Issue by garcia-jj** [caelum/vraptor-cdi-provider#4]
The plugin must be under <code>br.com.caelum.vraptor</code> group (as declared in readme). But in <code>pom.xml</code> was declared as <code>br.com.caelum</code>.

**Comment by lucascs** [comment]
Must it?

**Comment by garcia-jj** [comment]
All current plugins are declared under <code>br.com.caelum.vraptor</code> group. Only vraptor is declared under <code>br.com.caelum</code>. 

Readme or pom.xml must be changed to same location.
